TARGET = programmers_test
APP_SRCS = main.cpp \
		   lessons_12906/sjpark.cpp \
		   lessons_12909/sjpark.cpp

all:
	g++ -std=c++11 $(APP_SRCS) -lgtest -lpthread -o $(TARGET)

clean:
	rm -rf $(TARGET)
